name: PHP Project

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  php-application-build:
    runs-on: ubuntu-latest
    name: Run build

    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.VB_API_KEY }}
          job_status: ${{ job.status }}

      - uses: actions/checkout@v4

      - name: Set up PHP 8.1 with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies (retry logic)
        run: |
          for i in 1 2 3; do
            composer install --no-interaction && break || sleep 10
          done

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"
